Add `async_stub` method
pytest-dev/pytest-mock pull request #296
Opened 2022-06-19 11:47 UTC by PerchunPak

Which actually the same as `stub` but creates async stub.

2022-06-19 11:52 UTC, PerchunPak commented on docs/usage.rst
> +    ``async_stub`` method, which actually the same as ``stub`` but makes async stub.
![image](https://user-images.githubusercontent.com/68118654/174479531-3b781c11-db0a-4b2a-8c44-e966548615f0.png)

2022-06-24 11:56 UTC, nicoddemus requested changes
Thanks a lot @PerchunPak for the contribution, sorry about the delay. 

There are some things that need fixing:

1. Can you take a look at the test failures? Seems like we have to put a guard around the definition of `async_stub` on the Python versions that don't support it.
2. Could you add a very simple test to `TestMockerStub` that just calls `async_stub` and ensures it is an instance of `unittest.mock.AsyncMock`? This is just to avoid future regressions. The test needs to be skipped on unsupported Python versions.
3. Finally could add a quick changelog entry for this, under a new session `3.8.0 (unreleased)`?

Thanks again!

2022-06-24 16:10 UTC, PerchunPak commented
> Can you take a look at the test failures? Seems like we have to put a guard around the definition of async_stub on the Python versions that don't support it.

Can't imagine how, seems like `mock_module.AsyncMock` will not work with type checkers, so how this could be done?
Maybe import standalone `mock` module in `if TYPE_CHECKING:` block?

2022-06-24 16:21 UTC, nicoddemus commented
Sorry I should have mention, but [mypy supports `sys.version_info` checks](https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks). 👍

2022-06-24 16:23 UTC, PerchunPak commented
> Sorry I should have mentioned, but [mypy supports `sys.version_info` checks](https://mypy.readthedocs.io/en/stable/common_issues.html#python-version-and-system-platform-checks). 👍

Yes, but how about runtime? Yes `unittest.mock` doesn't have `AsyncMock` in py3.7, but `mock` have.

2022-06-24 16:24 UTC, nicoddemus commented
I'm OK with only supporting AsyncMock for Python 3.8+, or is this something you need in Python 3.7?

2022-06-24 16:28 UTC, PerchunPak commented
> I'm OK with only supporting AsyncMock for Python 3.8+, or is this something you need in Python 3.7?

No, just you support both (`unittest.mock` and `mock`), it's strange that you breaking this support here.

2022-06-24 17:15 UTC, nicoddemus commented
Hmm an alternative would be then:

```python
if sys.version_info[:2] >= (3, 8):
    AsyncMockType = unittest.mock.AsyncMock
else:
    AsyncMockType = mock.AsyncMock
```

at the top of the file, then use `AsyncMockType` in the annotation. If the above does not work, then `AsyncMockType = Any` for Python 3.7 is a good compromise.

2022-06-24 18:22 UTC, nicoddemus commented
Awesome, thanks a lot for the contribution and patience! 🙇

2022-06-24 18:23 UTC, merged